### ISSUE TITLE
Gdexporter ReferenceError: message is not defined

### ISSUE THREAD

**Issue by HiranChaudhuri** [arthuro555/gdexporter#5]
Quite some time ago I added gd-exporter into my ci-cd pipeline, and since then no longer worried about. Today I found out it is not processing successfully a project that I last changed 11 months ago. I cannot tell since when exactly it started failing. My first action was to improve error handling so I get notifications on failure. This part is not related to gdevelop.

But what is related is that gd-exporter fails with the message

```
📓 No config file found!
⌛ Loading plugins...
⌛ Loading GDCore...
🕗 Getting latest release tag...
❌ The GDevelop version was not found, downloading it!
🕗 Starting download of GDevelop Runtime 'v5.0.0-beta119'...
🕗 Starting download of GDevelop Core...
✅ Done downloading libGD.js
✅ Done downloading GDevelop Runtime 'v5.0.0-beta119'
🕗 Extracting GDevelop Runtime 'v5.0.0-beta119'...
✅ Done extracting the GDevelop Runtime
🕗 Compiling Runtime...
✅ Done downloading libGD.wasm
✅ Runtime built in 993ms
✅ Successfully downloaded GDevelop version 'v5.0.0-beta119'
⌛ Loading project...

[omitted some very long output]

ReferenceError: message is not defined
    at /usr/local/lib/node_modules/gdexporter/src/main.js:26:55
    at /usr/local/lib/node_modules/gdexporter/node_modules/gdcore-tools/src/downloadGD.js:195:59
    at Set.forEach (<anonymous>)
    at Object.onAbort (/usr/local/lib/node_modules/gdexporter/node_modules/gdcore-tools/src/downloadGD.js:195:37)
    at process.abort (/usr/local/lib/node_modules/gdexporter/node_modules/gdcore-tools/src/Versions/v5.0.0-beta119/libGD.js:9:15232)
    at process.emit (node:events:390:28)
    at emit (node:internal/process/promises:136:22)
    at processPromiseRejections (node:internal/process/promises:242:25)
    at processTicksAndRejections (node:internal/process/task_queues:97:32
```

What can be the cause for this?

**Comment by HiranChaudhuri** [comment]
Confirmed. The problem no longer appears.
Thank you for the quick fix! :-)
